/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StreamersRouteImport } from './routes/streamers'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HelpRouteImport } from './routes/help'
import { Route as BoostRouteImport } from './routes/boost'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportSlugRouteImport } from './routes/support.$slug'
import { Route as StreamerIdRouteImport } from './routes/streamer.$id'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalPaymentsRouteImport } from './routes/legal.payments'
import { Route as LegalAcceptableUseRouteImport } from './routes/legal.acceptable-use'
import { Route as ApiCurrencyPreferenceRouteImport } from './routes/api/currency-preference'
import { Route as ApiRevealKeyRouteImport } from './routes/api/_reveal-key'
import { Route as OverlayDonationSlugRouteImport } from './routes/overlay.donation.$slug'
import { Route as OverlayWidgetSlugWidgetRouteImport } from './routes/overlay.widget.$slug.$widget'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamersRoute = StreamersRouteImport.update({
  id: '/streamers',
  path: '/streamers',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const BoostRoute = BoostRouteImport.update({
  id: '/boost',
  path: '/boost',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportSlugRoute = SupportSlugRouteImport.update({
  id: '/support/$slug',
  path: '/support/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamerIdRoute = StreamerIdRouteImport.update({
  id: '/streamer/$id',
  path: '/streamer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPaymentsRoute = LegalPaymentsRouteImport.update({
  id: '/legal/payments',
  path: '/legal/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAcceptableUseRoute = LegalAcceptableUseRouteImport.update({
  id: '/legal/acceptable-use',
  path: '/legal/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCurrencyPreferenceRoute = ApiCurrencyPreferenceRouteImport.update({
  id: '/api/currency-preference',
  path: '/api/currency-preference',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRevealKeyRoute = ApiRevealKeyRouteImport.update({
  id: '/api/_reveal-key',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayDonationSlugRoute = OverlayDonationSlugRouteImport.update({
  id: '/overlay/donation/$slug',
  path: '/overlay/donation/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayWidgetSlugWidgetRoute = OverlayWidgetSlugWidgetRouteImport.update({
  id: '/overlay/widget/$slug/$widget',
  path: '/overlay/widget/$slug/$widget',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/boost': typeof BoostRoute
  '/help': typeof HelpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/streamers': typeof StreamersRoute
  '/studio': typeof StudioRoute
  '/tasks': typeof TasksRoute
  '/api': typeof ApiRevealKeyRoute
  '/api/currency-preference': typeof ApiCurrencyPreferenceRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/payments': typeof LegalPaymentsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/streamer/$id': typeof StreamerIdRoute
  '/support/$slug': typeof SupportSlugRoute
  '/overlay/donation/$slug': typeof OverlayDonationSlugRoute
  '/overlay/widget/$slug/$widget': typeof OverlayWidgetSlugWidgetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/boost': typeof BoostRoute
  '/help': typeof HelpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/streamers': typeof StreamersRoute
  '/studio': typeof StudioRoute
  '/tasks': typeof TasksRoute
  '/api': typeof ApiRevealKeyRoute
  '/api/currency-preference': typeof ApiCurrencyPreferenceRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/payments': typeof LegalPaymentsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/streamer/$id': typeof StreamerIdRoute
  '/support/$slug': typeof SupportSlugRoute
  '/overlay/donation/$slug': typeof OverlayDonationSlugRoute
  '/overlay/widget/$slug/$widget': typeof OverlayWidgetSlugWidgetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/boost': typeof BoostRoute
  '/help': typeof HelpRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/streamers': typeof StreamersRoute
  '/studio': typeof StudioRoute
  '/tasks': typeof TasksRoute
  '/api/_reveal-key': typeof ApiRevealKeyRoute
  '/api/currency-preference': typeof ApiCurrencyPreferenceRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/payments': typeof LegalPaymentsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/streamer/$id': typeof StreamerIdRoute
  '/support/$slug': typeof SupportSlugRoute
  '/overlay/donation/$slug': typeof OverlayDonationSlugRoute
  '/overlay/widget/$slug/$widget': typeof OverlayWidgetSlugWidgetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/boost'
    | '/help'
    | '/leaderboard'
    | '/profile'
    | '/services'
    | '/streamers'
    | '/studio'
    | '/tasks'
    | '/api'
    | '/api/currency-preference'
    | '/legal/acceptable-use'
    | '/legal/payments'
    | '/legal/privacy'
    | '/legal/terms'
    | '/streamer/$id'
    | '/support/$slug'
    | '/overlay/donation/$slug'
    | '/overlay/widget/$slug/$widget'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/boost'
    | '/help'
    | '/leaderboard'
    | '/profile'
    | '/services'
    | '/streamers'
    | '/studio'
    | '/tasks'
    | '/api'
    | '/api/currency-preference'
    | '/legal/acceptable-use'
    | '/legal/payments'
    | '/legal/privacy'
    | '/legal/terms'
    | '/streamer/$id'
    | '/support/$slug'
    | '/overlay/donation/$slug'
    | '/overlay/widget/$slug/$widget'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/boost'
    | '/help'
    | '/leaderboard'
    | '/profile'
    | '/services'
    | '/streamers'
    | '/studio'
    | '/tasks'
    | '/api/_reveal-key'
    | '/api/currency-preference'
    | '/legal/acceptable-use'
    | '/legal/payments'
    | '/legal/privacy'
    | '/legal/terms'
    | '/streamer/$id'
    | '/support/$slug'
    | '/overlay/donation/$slug'
    | '/overlay/widget/$slug/$widget'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BoostRoute: typeof BoostRoute
  HelpRoute: typeof HelpRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ProfileRoute: typeof ProfileRoute
  ServicesRoute: typeof ServicesRoute
  StreamersRoute: typeof StreamersRoute
  StudioRoute: typeof StudioRoute
  TasksRoute: typeof TasksRoute
  ApiRevealKeyRoute: typeof ApiRevealKeyRoute
  ApiCurrencyPreferenceRoute: typeof ApiCurrencyPreferenceRoute
  LegalAcceptableUseRoute: typeof LegalAcceptableUseRoute
  LegalPaymentsRoute: typeof LegalPaymentsRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  StreamerIdRoute: typeof StreamerIdRoute
  SupportSlugRoute: typeof SupportSlugRoute
  OverlayDonationSlugRoute: typeof OverlayDonationSlugRoute
  OverlayWidgetSlugWidgetRoute: typeof OverlayWidgetSlugWidgetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streamers': {
      id: '/streamers'
      path: '/streamers'
      fullPath: '/streamers'
      preLoaderRoute: typeof StreamersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boost': {
      id: '/boost'
      path: '/boost'
      fullPath: '/boost'
      preLoaderRoute: typeof BoostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/$slug': {
      id: '/support/$slug'
      path: '/support/$slug'
      fullPath: '/support/$slug'
      preLoaderRoute: typeof SupportSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streamer/$id': {
      id: '/streamer/$id'
      path: '/streamer/$id'
      fullPath: '/streamer/$id'
      preLoaderRoute: typeof StreamerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/payments': {
      id: '/legal/payments'
      path: '/legal/payments'
      fullPath: '/legal/payments'
      preLoaderRoute: typeof LegalPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/acceptable-use': {
      id: '/legal/acceptable-use'
      path: '/legal/acceptable-use'
      fullPath: '/legal/acceptable-use'
      preLoaderRoute: typeof LegalAcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/currency-preference': {
      id: '/api/currency-preference'
      path: '/api/currency-preference'
      fullPath: '/api/currency-preference'
      preLoaderRoute: typeof ApiCurrencyPreferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/_reveal-key': {
      id: '/api/_reveal-key'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRevealKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/donation/$slug': {
      id: '/overlay/donation/$slug'
      path: '/overlay/donation/$slug'
      fullPath: '/overlay/donation/$slug'
      preLoaderRoute: typeof OverlayDonationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/widget/$slug/$widget': {
      id: '/overlay/widget/$slug/$widget'
      path: '/overlay/widget/$slug/$widget'
      fullPath: '/overlay/widget/$slug/$widget'
      preLoaderRoute: typeof OverlayWidgetSlugWidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BoostRoute: BoostRoute,
  HelpRoute: HelpRoute,
  LeaderboardRoute: LeaderboardRoute,
  ProfileRoute: ProfileRoute,
  ServicesRoute: ServicesRoute,
  StreamersRoute: StreamersRoute,
  StudioRoute: StudioRoute,
  TasksRoute: TasksRoute,
  ApiRevealKeyRoute: ApiRevealKeyRoute,
  ApiCurrencyPreferenceRoute: ApiCurrencyPreferenceRoute,
  LegalAcceptableUseRoute: LegalAcceptableUseRoute,
  LegalPaymentsRoute: LegalPaymentsRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  StreamerIdRoute: StreamerIdRoute,
  SupportSlugRoute: SupportSlugRoute,
  OverlayDonationSlugRoute: OverlayDonationSlugRoute,
  OverlayWidgetSlugWidgetRoute: OverlayWidgetSlugWidgetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
